# Generated by Django 5.1.7 on 2025-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='approval',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='severity',
            field=models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
