# Generated by Django 5.1.2 on 2025-03-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_diagnosis_approval_alter_diagnosis_severity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='doctor',
            new_name='doctor_id',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
